version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: acrilico_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - acrilico_network

  adminer:
    image: adminer
    container_name: acrilico_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - acrilico_network

volumes:
  postgres_data:

networks:
  acrilico_network:
    driver: bridge